config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'

  get '/about', to: "pages#about", as: :about_us

  get '/contact', to: "pages#contact"
  # verb        to: 'controller#action'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @time = Date.today.strftime("%B #{Date.today.day.ordinalize}")
  end

  def about
  end

  def contact
    search = params[:member]

    @members = ['Ben', 'Rebecca', 'Katherine', 'Alex', 'Celine', 'Lucien']

    if search.present?
      @members = @members.select { |name| name.start_with?(search) }
    end

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstRailsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="background: lightgray; padding: 16px">
      <ul>
        <li><%= link_to "Learn about us", about_us_path %></li>
        <li><%= link_to "Contact us", contact_path %></li>
      </ul>
      <form action="/contact" method="get">
        <input type="text" name="member" placeholder="Who are you looking for?" value="<%= params[:member] %>">
        <input type="submit">
      </form>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the page eplaining our website</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Laudantium fuga, voluptatibus esse est facilis. Eum voluptas totam reprehenderit incidunt cum voluptatibus ducimus nostrum illum commodi. Itaque autem, temporibus tenetur ab.</p>

app/views/pages/contact.html.erb
<h1>Contact us</h1>

<ul>
  <% @members.each do |name| %>
    <li><%= name %></li>
  <% end %>
</ul>

app/views/pages/home.html.erb
<h1>Welcome to our website</h1>

<p>Today it is <strong><%= @time %></strong></p>